name: Merge

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
  deploy_function:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Deploy a Cloud Function"
        id: deploy-function
        uses: google-github-actions/deploy-cloud-functions@v0.1.0
        with:
          name: cloud-segmentation
          runtime: python37
          project_id: ${{ secrets.gcp_project_id }}
          credentials: ${{ secrets.gcp_credentials }}
          entry_point: run_inference
          env_vars: INPUT_BUCKET_NAME=cloud-segmentation-input,OUTPUT_BUCKET_NAME=cloud-segmentation-output
          memory_mb: 2048MB
